services:
  - type: web
    name: esc-guidelines-search
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    disk:
      name: esc-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

